name: 'page2pdf'
description: 'page2pdf'
inputs:
  url:
    description: 'page url'
    required: true
outputs:
  domain:
    description: 'domain'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.url }}