name: hackernews
on:
  push:
  schedule:
    - cron: '0 19 * * *'

jobs:
  hackernews:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: page2pdf
        uses: ./
        with:
          url: 'https://news.ycombinator.com'
      - name: print page2pdf output
        run: echo "domain was ${{ steps.page2pdf.outputs.domain }}"
      - name: email
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp-mail.outlook.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: hackernews
          body: RT
          to: yuqing.ji@outlook.com
          from: yuqing.ji@outlook.com
          attachments: ${{ steps.page2pdf.outputs.domain }}.pdf