jobs:
  page2pdf:
    runs-on: ubuntu-latest
    name: page2pdf
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: ./
        with:
          url: 'https://gniquyij.github.io'