name: send2kindle

on:
  repository_dispatch:
    types: send2kindle

jobs:
  send2kindle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: page2pdf
        uses: gniquyij/page2pdf@v1.0.0
        with:
          url: ${{ github.event.client_payload.text }}
      - name: send2kindle
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp-mail.outlook.com
          server_port: 587
          username: ${{ secrets.EMAIL }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: ${{ github.event.client_payload.text }}
          body: RT
          to: ${{ secrets.KINDLE_EMAIL }}
          from: yuqing.ji@outlook.com
          attachments: ${{ steps.page2pdf.outputs.domain }}.pdf